#ifndef	DYNAMICARROWMANAGERSSE_VERSION_INCLUDED
#define DYNAMICARROWMANAGERSSE_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define DYNAMICARROWMANAGERSSE_VERSION_MAJOR	1
#define DYNAMICARROWMANAGERSSE_VERSION_MINOR	0
#define DYNAMICARROWMANAGERSSE_VERSION_PATCH	1
#define DYNAMICARROWMANAGERSSE_VERSION_BETA		0
#define DYNAMICARROWMANAGERSSE_VERSION_VERSTRING	MAKE_STR(DYNAMICARROWMANAGERSSE_VERSION_MAJOR) "." MAKE_STR(DYNAMICARROWMANAGERSSE_VERSION_MINOR) "." MAKE_STR(DYNAMICARROWMANAGERSSE_VERSION_PATCH) "." MAKE_STR(DYNAMICARROWMANAGERSSE_VERSION_BETA)

#endif
